{{- if .Values.msvc.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: airbnb-msvc
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: management
      port: 8081
      targetPort: 8081
  selector:
    app: airbnb-msvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airbnb-msvc
spec:
  replicas: {{ .Values.msvc.replicaCount }}
  selector:
    matchLabels:
      app: airbnb-msvc
  template:
    metadata:
      labels:
        app: airbnb-msvc
      {{- if .Values.istio.enabled }}
      annotations:
        sidecar.istio.io/inject: "true"
        prometheus.istio.io/merge-metrics: "true"
        proxy.istio.io/config: |
          tracing:
            sampling: {{ .Values.istio.telemetry.tracing.randomSamplingPercentage }}
      {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: airbnb-msvc
          image: "{{ .Values.msvc.image.repository }}:{{ .Values.msvc.image.tag }}"
          imagePullPolicy: {{ .Values.msvc.image.pullPolicy }}
          ports:
            - containerPort: 8080
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/{{ .Values.msvc.env.POSTGRES_DB }}"
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.msvc.env.POSTGRES_USER | quote }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.msvc.env.POSTGRES_PASSWORD | quote }}
            - name: SPRING_ELASTICSEARCH_URIS
              value: {{ .Values.msvc.env.SPRING_ELASTICSEARCH_URIS | quote }}
            - name: SPRING_DATA_REDIS_HOST
              value: {{ .Values.msvc.env.SPRING_DATA_REDIS_HOST | quote }}
            - name: SPRING_DATA_REDIS_PORT
              value: {{ .Values.msvc.env.SPRING_DATA_REDIS_PORT | quote }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.msvc.env.OTEL_EXPORTER_OTLP_ENDPOINT | quote }}
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: {{ .Values.msvc.env.OTEL_EXPORTER_OTLP_PROTOCOL | quote }}
            - name: OTEL_TRACES_EXPORTER
              value: {{ .Values.msvc.env.OTEL_TRACES_EXPORTER | quote }}
            - name: OTEL_METRICS_EXPORTER
              value: {{ .Values.msvc.env.OTEL_METRICS_EXPORTER | quote }}
            - name: OTEL_LOGS_EXPORTER
              value: {{ .Values.msvc.env.OTEL_LOGS_EXPORTER | quote }}
            - name: OTEL_TRACES_SAMPLER
              value: {{ .Values.msvc.env.OTEL_TRACES_SAMPLER | quote }}
            - name: OTEL_METRIC_EXPORT_INTERVAL
              value: {{ .Values.msvc.env.OTEL_METRIC_EXPORT_INTERVAL | quote }}
            - name: OTEL_PROPAGATORS
              value: {{ .Values.msvc.env.OTEL_PROPAGATORS | quote }}
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: {{ .Values.msvc.env.OTEL_RESOURCE_ATTRIBUTES | quote }}
            - name: OTEL_INSTRUMENTATION_LOGBACK_APPENDER_ENABLED
              value: {{ .Values.msvc.env.OTEL_INSTRUMENTATION_LOGBACK_APPENDER_ENABLED | quote }}
            - name: OTEL_INSTRUMENTATION_LOGBACK_APPENDER_EXPERIMENTAL_LOG_ATTRIBUTES
              value: {{ .Values.msvc.env.OTEL_INSTRUMENTATION_LOGBACK_APPENDER_EXPERIMENTAL_LOG_ATTRIBUTES | quote }}
            - name: OTEL_INSTRUMENTATION_LOGBACK_APPENDER_EXPERIMENTAL_CAPTURE_MDC_ATTRIBUTES
              value: {{ .Values.msvc.env.OTEL_INSTRUMENTATION_LOGBACK_APPENDER_EXPERIMENTAL_CAPTURE_MDC_ATTRIBUTES | quote }}
            - name: OTEL_INSTRUMENTATION_COMMON_DEFAULT_ENABLED
              value: {{ .Values.msvc.env.OTEL_INSTRUMENTATION_COMMON_DEFAULT_ENABLED | quote }}
            - name: OTEL_JAVAAGENT_DEBUG
              value: {{ .Values.msvc.env.OTEL_JAVAAGENT_DEBUG | quote }}
            - name: OTEL_SERVICE_NAME
              value: airbnbSearcher
            - name: APP_LOG_LEVEL
              value: {{ .Values.msvc.env.APP_LOG_LEVEL | quote }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
{{- end }}
